name: Trigger auto deployment for test-oct-2025-aca

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/test-oct-2025-aca-AutoDeployTrigger-1adc9d28-4005-46b8-8273-979a71a8773d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.TESTOCT2025ACA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TESTOCT2025ACA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TESTOCT2025ACA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: asclabcrh6vljfvk5qhoy.azurecr.io
          registryUsername: ${{ secrets.TESTOCT2025ACA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TESTOCT2025ACA_REGISTRY_PASSWORD }}
          containerAppName: test-oct-2025-aca
          resourceGroup: asclab
          imageToBuild: asclabcrh6vljfvk5qhoy.azurecr.io/test-oct-2025-aca:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


